name: Laravel Release

on:
  push:
    tags:
      - "v*"

jobs:
  zip-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev --ignore-platform-req=php+
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16
          check-latest: true
      - name: Install NPM dependencies
        run: npm install
      - name: Compile front-end assets
        run: npm run build
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig vite.config.js phpunit.xml postcss.config.js\
                       docker-compose.yml jsconfig.json tailwind.config.json /*resources/css/* /*resources/js/*\
                       /*queries/* /*storage/debugbar/* /*database/factories/* /*database/seeders/* /*tests/*'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
